sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RW1X7dct221tRwkczPJAwK2tmi3zIUogkDQT98zhXL5vP69QZqMFs/ljVDR+Sa/3CC8F0lnCBP+0dir0e3K/Fip1/5UTBQaW//BicBH4Tb4EDA2UnQfJ05zCQJD7vsHxIRuAPHGVFT/GaGU8fEINzxEGabJYqXBhxXWmLa6kR202EObPg67YpmbVP/hanMoDXCyyvunGyf/h/3XvUtmUuXsR4HHUUpWguE4fBoFwmkSSlh5MAlioEXm3yGrEjHDF7iNkGxabiw8tXCiaz6XJbPRzj/Qb2gQrsdVh2IaZgZP52CvpXApsNQVuvREsaEG9hV3a/ZYrTPDw62hbOQMPD4JoS+xlpyes3VFCjQsgbx767yJQ2UQ78VeWfY0TKKcxawyr57fKMXrSrUwZMiBlPmAD9/g/GlhfSq4/sdir8kKBpmrUsKbCea/+ds2qUrSj7vRPsO6/XHYFqbJZ9LOVj+Y1cXYgrxxZIlEc/mKIfksYswI2DY/SWKsRrCBF0gWupa3eJ0U4Kp8X1y2V28LaEPk1cuvxqq7DHnMFoFvWoSRqMQJ2tq1jb381buph/NDu57PTwESRSGi+gaOmz2UHWnYLTiXPnMjEzm9KQAgaTPTeJJynU9rwP6wUFZ5eooSHFCK5NLFIYe5MyL5ZO1SgP6zndPA18RM4pLT4lbxIcVY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Following-the-Equator--A-Journey-Around-the-World.-Part-7_5814
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy